---
dryRun: false
verbosity: "DEBUG"
scheme: "SEMVER"
initialVersion: "1.0.0"
releaseLenient: false

summary: true
stateFile: ".nyx-state.yaml"
resume: true
sharedConfigurationFile: ".nyx-shared-bump.yml"

commitMessageConventions/enabled: []

substitutions:
  enabled:
    - ruby
    - changelog_fragment
    - changelog_version_link
  items:
    ruby:
      files: "**/lib/*/version.rb"
      match: "VERSION(\\s)*=(\\s)*\"(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\""
      replace: "VERSION = \"{{version}}\""
    changelog_fragment:
      files: "**/CHANGELOG.md"
      match: "(?s)(?m)(# Changelog)(.*?)(## \\[\\d)"
      replace: >-
        $1$2## [{{version}}] - {{#timeFormat format="2006-01-02"}}{{timestamp}}{{/timeFormat}}


        {{#fileContent}}.nyx-cc-fragment.md{{/fileContent}}$3
    changelog_version_link:
      files: "**/CHANGELOG.md"
      match: "(?s)(?m)(\\A.*?)(?=((?:^\\[(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)\\]:\\shttp.*)|\\z))"
      replace: "$1[{{version}}]: https://github.com/{{configuration.services.github.options.REPOSITORY_OWNER}}/{{configuration.services.github.options.REPOSITORY_NAME}}/releases/tag/{{version}}\n\n"

git:
  remotes:
    origin:
      authenticationMethod: PUBLIC_KEY
      privateKey: ".ssh/skopciewski"

releaseTypes:
  enabled:
    - mainline
  publicationServices:
    - github
  items:
    mainline:
      collapseVersions: false
      filterTags: "^({{configuration.releasePrefix}})?([0-9]\\d*)\\.([0-9]\\d*)\\.([0-9]\\d*)$"
      gitCommit: true
      gitCommitMessage: "Release version {{version}}"
      gitPush: true
      gitPushForce: true
      gitTag: true
      gitTagForce: true
      gitTagMessage: "Tag release {{version}}"
      gitTagNames:
        - "{{version}}"
        - "latest"
      matchBranches: "^(master|main)$"
      matchEnvironmentVariables:
      matchWorkspaceStatus:
      publish: true
      releaseName: "{{configuration.services.github.options.REPOSITORY_NAME}} {{version}}"
      description: "{{#fileContent}}.nyx-cc-fragment.md{{/fileContent}}"
      versionRangeFromBranchName: false

services:
  github:
    type: "GITHUB"
    options:
      AUTHENTICATION_TOKEN: "{{#environmentVariable}}GITHUB_TOKEN{{/environmentVariable}}"
      REPOSITORY_OWNER: "skopciewski"
      REPOSITORY_NAME: "srtest"
